### ISSUE TITLE
Installed distribution requests 1.2.3 conflicts with requirement requests>=2.2.1

### ISSUE THREAD

**Issue by Baggz** [apiaryio/black-belt#104]
Hi,

I'm trying to update BB to the latest version, but it fails.

```
easy_install -U blackbelt
Searching for blackbelt
Reading https://pypi.python.org/simple/blackbelt/
Best match: blackbelt 0.11.12
Processing blackbelt-0.11.12-py2.7.egg
blackbelt 0.11.12 is already the active version in easy-install.pth
Installing bb script to /usr/local/bin

Using /Library/Python/2.7/site-packages/blackbelt-0.11.12-py2.7.egg
Processing dependencies for blackbelt
error: Installed distribution requests 1.2.3 conflicts with requirement requests>=2.2.1
```

What am I doing wrong?

Thanks!

**Comment by honzajavorek** [comment]
I don't experience anything like that with `pip` :-| I don't say it's solution, but if you want just painkiller, then

```
$ easy_install pip
$ pip install blackbelt -U
```

**Comment by Baggz** [comment]
Fixed.

Thanks, @honzajavorek!

**Comment by honzajavorek** [comment]
@Baggz `pip` is Python's `npm`. `easy_install` is sort of legacy installer, but it's sometimes used in tutorials for non-Python people, because it's usually already present on every system. `pip` has to be installed first. One joke says `easy_install` is just good for installing `pip` ;)
