### ISSUE TITLE
Difference in message if deploy to staging/production

### ISSUE THREAD

**Issue by abtris** [apiaryio/black-belt#110]
Would it be possible to highlight (make it bold) ’staging’ (or ‘production’)?
 Or use a different bot—Production Deploy, Staging Deploy (instead of Black Belt).

From @Baggz

**Comment by abtris** [comment]
All can be possible, but I need some time to decide how we make it.

@honzajavorek  @Almad any suggestions to this topic?

**Comment by honzajavorek** [comment]
Are you looking for opinions on how to implement it in code or how it should work in overall (two bots vs. highlighted message)?

**Comment by abtris** [comment]
Opinion about usage and visibility. Implementing will be easy. I can modify bot name or meassage. We have to what's better.

**Comment by abtris** [comment]
Migrated to apiaryio/bb#35
