### ISSUE TITLE
Get Unassigned PRs

### ISSUE THREAD

**Issue by smizell** [apiaryio/black-belt#114]
This is a wish list for me.

As a team member who watches several repositories, so that I don't have to manually hit each repository to get a list of the unassigned PRs, I would love to be able to provide a list of repositories and check those periodically with Black Belt.

**Comment by abtris** [comment]
For this is at mac this app - http://ptsochantaris.github.io/trailer/

**Comment by smizell** [comment]
Very cool. Do you use this?

**Comment by abtris** [comment]
Yes, I'm using this 2 years.

**Comment by smizell** [comment]
Interesting. I don't see a way to view just the unassigned PRs in the repo so I know what PRs need to be reviewed. I'll keep digging.

**Comment by abtris** [comment]
I look for all PR, but this case isn't covered but you can create issue and discuss with author. He is very open to new use cases. https://github.com/ptsochantaris/trailer/issues

**Comment by abtris** [comment]
Migrated to apiaryio/bb#33
