### ISSUE TITLE
Create card from template

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#119]
Proposal on how the feature could work.
#### With Link to Template

```
$ bb t from-template http://trello.com/link-to-template-card
```

Creates a new card in the same board and column using given template card. Opens the resulting card in your browser.
#### With Link to Board (a.k.a. I'm lazy to lookup, copy and paste the template link)

```
$ bb t from-template http://trello.com/link-to-board
Columns:
1: To Do
2: Bug
3: Done
Which column? 2
```

Creates a new templated card in the given board. Interactively asks for a column and treats the first card in selected column as a template card. Creates new card using the template card and opens it in your browser.

**Comment by Almad** [comment]
@honzajavorek Hm, I'd do interactive only with `-i` switch and stick to what `bb` does with other commands: default assumptions.

The way I think workflow around those should work, I think it should put it into `Inbox` by default.

**Comment by Almad** [comment]
Also, I think it actually make more sense to

`bb t copy-checklist http://trello.com/template-card http://trello.com/story-card`, so that story card can enter using normal workflow and when scheduled for sprint, they'd get the completion checklist

**Comment by abtris** [comment]
Can template copy all content of template? or skip attachments? What typical  template card can included?

**Comment by Almad** [comment]
...and `bb t prepare-story http://trello.com/story-card` with a defaulted template card :)

**Comment by honzajavorek** [comment]
- I'm OK with `-i`, first column / Inbox could be the default option.
- `copy-checklist` wouldn't copy headings in description, right?
- How would `bb t prepare-story http://trello.com/story-card` work? I would create story card myself and this would just take it and add *some* stuff from the *closest* template card into it?

The only case when I'd use this personally (since I'm not a PO and I'm never creating stories) is to add something to the Product Inbox according to a template. Then I'd prefer behavior I described. POs and Completion List might be a slightly different case after all, I don't know. Maybe POs don't even need this automated :neutral_face:

**Comment by Almad** [comment]
> copy-checklist wouldn't copy headings in description, right?

Yes, and I'd say that's intentional. Is there anything that should be captured as a heading/description and not a checklist?

> How would bb t prepare-story http://trello.com/story-card work? I would create story card myself and this would just take it and add some stuff from the closest template card into it?

No, it would take story card and `copy-checklist` there from default template card.

**Comment by honzajavorek** [comment]
> Is there anything that should be captured

Look at the current shape of e.g. Bug template:

<img width="349" alt="screen shot 2016-04-11 at 15 12 08" src="https://cloud.githubusercontent.com/assets/283441/14428127/f7e0b75e-fff7-11e5-8f89-6f8f1ff3903a.png">

> default template card

How would *default template card* be defined? In `~/.blackbelt`?

--------

Maybe templated bug etc. cards are something else than templated story cards, have different use cases and shouldn't be treated together. E.g. *default template card* wouldn't work for cards in Product Inbox at all since every column has it's own template.

**Comment by Almad** [comment]
@honzajavorek yes, and I think that the completion template card should be different one, and I am not afraid to make bb specific to our workflow, at least until someone complains / says they're using it too.

thus, yes, two special cases and templated card in config and with hardcoded defaults akin to https://github.com/apiaryio/black-belt/blob/master/blackbelt/config.py#L40 :)

**Comment by abtris** [comment]
Migrated to apiaryio/bb#30
