### ISSUE TITLE
bb gh deploy should abort in some cases

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#124]
`bb gh deploy` should abort if there is "no deploy window” or if `master` is not green on this page: https://github.com/apiaryio/apiary/branches.

**Comment by abtris** [comment]
Can we close this, abort for master is done. I'm not sure how we can implement no deploy window.

**Comment by honzajavorek** [comment]
All no deploy Windows should be in the Production Events Calendar. Can we
just check the Calendar? I hope Google Calendar API wont be necessary and
it has just a simple iCal feed. There is an iCal library for Python, we use
it on pyvo.cz.

**Comment by honzajavorek** [comment]
We don't have any tracking of no deploy windows anymore.
