### ISSUE TITLE
bb dep check should support local directory

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#152]
@kuba-kubula found an interesting use case - he has a GitHub repo containing a package.json with dependencies, but the package is not published to any registry.

In this case, black belt cannot help him. It would be nice if it could work with local directory as well:

```
$ bb dep check react@1.2.3  # now
$ bb dep check ./my/local/path  # feature this issue is about
```

**Comment by Almad** [comment]
😱  What package is this?

**Comment by honzajavorek** [comment]
Not mentioning that anything else than npm packages isn't automated right now (Py deps, Ruby deps, CSS frameworks, ...). Maybe some of the `dep` tools could get decoupled so we can use them also separately - e.g. the licenses parser / Public License Field creator.

**Comment by honzajavorek** [comment]
IMHO implemented in https://github.com/apiaryio/black-belt/pull/173
