### ISSUE TITLE
bb dep check should let you know "breadcrumbs" to the problematic library

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#170]
Often there are problematic libraries deep in the dependency tree and it's hard to track down the chain of parent libraries which introduces the problem. Sometimes to resolve the issue it could be sufficient to just upgrade versions on the way, but current `bb dep check` output doesn't give any clues on the chain. Therefore `bb` should print also "breadcrumbs" like

```
dredd@x.x » react@x.x.x » colors@x.x » left-pad@x.x
```

**Comment by opichals** [comment]
@honzajavorek This would indeed be very nice. Currently I use `npm-consider` for tracing the tree. It outputs a nice table of dependencies.

`npx npm-consider install dredd@x.x` 

see https://medium.com/@vovabilonenko/licenses-of-npm-dependencies-bacaa00c8c65 for more

**Comment by honzajavorek** [comment]
Currently I have a sandbox directory where I do `npm install dredd@x.x`. When install finishes, it prints the tree. I then use my eyes to figure out the breadcrumbs, which is a poor solution as I tend to fail in following the vertical lines 😄 

I did not know about `npm-consider`, will look at it.
