### ISSUE TITLE
Deploying to staging could identify the previous person using staging

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#172]
When using `bb stage`, it could look into previous deploys on Heroku and identify who was the last one to use staging. If the last deploy to staging was less than 24 hours, it would ask the last deployer in the `#deploy-queue` whether they're fine with a new deploy, and ask the blackbelt user y/N whether to continue.

**Comment by abtris** [comment]
Migrated to apiaryio/bb#21
