### ISSUE TITLE
Improve the npm install experience of bb dep check

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#178]
IMHO the best experience would be:

1. `bb dep check <nonexisting>` => `Error: The npm package does not exist`
2. `bb dep check <existing>@<nonexisting>` => `Error: The version does not exist (available: 1.2, 1.1, 1.0...)` (printing last three from `npm view <existing> versions --json`
3. `bb dep check <existing-but-failing-to-install>` => `Error: The npm package could not be installed`
4. `bb dep check <existing-but-failing-to-install> --debug` => prints also the npm output

**Comment by abtris** [comment]
Migrated to apiaryio/bb#18
