### ISSUE TITLE
bb dep check should list projects without license as first ones

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#180]
We need to solve those with priority and such a small change as just sorting out the blackbelt's output would help a lot to realize the size of the problems and to start solving them.

**Comment by honzajavorek** [comment]
We should have clear three categories:

1. Dependencies approved for Apiary in the TPLTA (green)
2. Dependencies eligible to pre-approval (blue)
3. Dependencies eligible to approval (yellow) - dual licensing, non-standard license, crypto, ...
4. Dependencies with no chance to get ever approved (red) - missing full license text

The first point cannot be done unless Black Belt's source is closed. Also, black belt needs to clearly distinguish unknown (non-standard) licenses from missing licenses.

**Comment by abtris** [comment]
Migrated to apiaryio/bb#17
