### ISSUE TITLE
json-schema@0.2.3 gets LICENSE ignored, README is read instead

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#182]
This is unfortunate as the main license text is obviously in the LICENSE file, there is only some additional info in the README

**Comment by honzajavorek** [comment]
The same goes for cssstyle@1.1.1, the license is in `MIT-LICENSE.txt` but `bb dep check cssstyle --debug` shows the README is considered as a license.

**Comment by abtris** [comment]
Migrated to apiaryio/bb#15
