### ISSUE TITLE
Missing copyright notices

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#183]
Many projects fall into "missing copyright notice" category, especially in case of Apache licenses. E.g. `doctrine@2.1.0` https://github.com/eslint/doctrine

We need to figure out how to solve this automatically. I've asked `license-checker` to implement getting copyright notices and they added it (!) but I did not have time to use this new feature in blackbelt and to play with it yet: https://github.com/davglass/license-checker/issues/154 It could possibly fix all these problems.

**Comment by abtris** [comment]
Migrated to apiaryio/bb#14
