### ISSUE TITLE
Verify License.txt gets detected correctly

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#184]
dom-helpers@3.3.1 has a full license text in `License.txt`, but blackbelt fails to detect it. I was improving `license-checker` algorithms for detecting the files in the past, so this should be just a matter of adding a test here https://github.com/davglass/license-checker/blob/master/tests/license-files-test.js and verifying where is the issue.

**Comment by abtris** [comment]
Migrated to apiaryio/bb#13
