### ISSUE TITLE
Dependencies patched by our internal tool should be listed in a different way

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#189]
Heavily related to https://github.com/apiaryio/black-belt/issues/180#issuecomment-419386384 and https://github.com/apiaryio/black-belt/issues/188

-----

When there are dependencies which we internally patched and fixed, they should be treated differently by blackbelt - probably assumed as pre-approval eligible and marked with a special color.

This is not possible to implement unless Black Belt is closed source.

**Comment by abtris** [comment]
Migrated to apiaryio/bb#10
