### ISSUE TITLE
code completion for bash, zsh

### ISSUE THREAD

**Issue by abtris** [apiaryio/black-belt#32]

**Comment by Almad** [comment]
Closing as `bash` is done and I have no idea about zsh. Please reopen if you'd have ideas how to provide those.

**Comment by abtris** [comment]
I found way for zsh, WIP version of zsh plugin is here https://github.com/abtris/dotfiles/blob/master/zsh/plugins/bb/_bb

**Comment by abtris** [comment]
I make basic version to cover all implemented features. Can I add autocomplete file somewhere into blackbelt directory or make some my separate only with zsh plugin for autocomplete?

**Comment by Almad** [comment]
@abtris I think adding it to bb subdir would be good.

I just don't like the complete duplicity. Do you think you could generate it from code, metaprogramming-style?

**Comment by abtris** [comment]
Can be possible but I don't know how in python.

**Comment by abtris** [comment]
Any suggestion how to make? Some examples?

**Comment by abtris** [comment]
Migrated to apiaryio/bb#43
