### ISSUE TITLE
Add link to the PR as an attachment

### ISSUE THREAD

**Issue by Baggz** [apiaryio/black-belt#41]
Add link to the PR as a card attachment.
## Preview

![image](https://cloud.githubusercontent.com/assets/95191/5359083/fce8c5de-7fba-11e4-944a-b892c689231d.png)

---

I'm new to Python, but will do my best.
- [ ] Extend [`trello.py`](https://github.com/apiaryio/black-belt/blob/master/blackbelt/apis/trello.py), add a new method to add an attachment _(API docs are at https://trello.com/docs/api/card/index.html#post-1-cards-card-id-or-shortlink-attachments)_.
- [ ] Call `add_attachment` in [`handle_github.py`](https://github.com/apiaryio/black-belt/blob/3022bb8d25ed925587a4f0bbfd157e9de6516ad4/blackbelt/handle_github.py#L104-L106).

**Comment by honzajavorek** [comment]
btw, [this](https://github.com/honzajavorek/film2trello/blob/master/film2trello/trello.py#L135:L137) is how you create attachments in Trello's API

**Comment by honzajavorek** [comment]
I don't think this is relevant as we're not using Trello for product development anymore. Feel free to reopen if you think something different.
