### ISSUE TITLE
Move card to ‘Doing’, reopen PR, push changes

### ISSUE THREAD

**Issue by Baggz** [apiaryio/black-belt#42]
Hi,

Let's say code review denied my PR _(and the reviewer closed the PR)_. Is there any command _(or plans)_ to...
1. Ditch the current card _(move it to ‘Blocking’, maybe)_
2. Move the Trello card back to _‘Doing’_
3. Reopen the PR
4. Push the changes

Thanks for the clarification!

**Comment by honzajavorek** [comment]
I don't think this is relevant as we're not using Trello for product development anymore. I'm not sure whether this could work with the Jira workflows. Feel free to reopen if you still want a feature like this.
