### ISSUE TITLE
Deployment API

### ISSUE THREAD

**Issue by Baggz** [apiaryio/black-belt#45]
Hi,

Would it be possible to use the [Deployment API](https://developer.github.com/v3/repos/deployments/) to mark a PR as deployed?

![image](https://cloud.githubusercontent.com/assets/95191/5376771/901f9714-807a-11e4-8982-6345d3979ab5.png)

_(I know you can open Trello and see the respective card.)_

**Comment by abtris** [comment]
:+1:

**Comment by honzajavorek** [comment]
@Almad I think multiple sources of the same truth are a good thing in case something blows up (aka platform support) and you need to quickly find a culprit PR/code/whatever. Switching back and forth between GitHub and Trello is... I am going to use "not convenient".

**Comment by Almad** [comment]
@honzajavorek Source of truth should be only one, but I agree that propagating it everywhere is a good idea. 

Primary source of truth is obviously heroku, primary source of review is Trello (because it retains whether it's just deployed, or verified as well).

**Comment by honzajavorek** [comment]
That's probably what I meant by "multiple sources of the same truth" and wrote it in a bad way :) We're on the same page.

**Comment by Almad** [comment]
@Baggz Is it fixed by #50 ?

**Comment by Almad** [comment]
(released as 0.11.4)

**Comment by XVincentX** [comment]
Looks like it is not working. I can't see the deploy informations in closed pull requests.

**Comment by Almad** [comment]
@XVincentX do you use 0.11.4?

**Comment by XVincentX** [comment]
Yes I do!
![image](https://cloud.githubusercontent.com/assets/1416224/6941761/dc40070e-d882-11e4-946a-403b8bf2b9e2.png)

**Comment by Baggz** [comment]
:+1:

**Comment by Almad** [comment]
@Baggz that is +1 for fixing or enhancing the PR? ;)

**Comment by Baggz** [comment]
@Almad 

Ah, sorry... It's ‘same here’ (= it's not working properly).

**Comment by abtris** [comment]
Migrated to apiaryio/bb#41
