### ISSUE TITLE
bb gh deploy - moving trello card failed

### ISSUE THREAD

**Issue by abtris** [apiaryio/black-belt#54]
Can be problem if card is not in `Work Overview`? It was in `Work Overview: SRE`.

```
Moving card failed. Open PR in browser? [True]:
```

**Comment by Almad** [comment]
@abtris is it in the board you've configured bb to, or in the default one? 

I am probably going to remove the default for work overview as it's clearly broken for most people ;)

**Comment by abtris** [comment]
Yes, I have configured `Work Overview: SRE` as work overview.

**Comment by Almad** [comment]
@abtris Is it fixed with 0.11.2?
