### ISSUE TITLE
Specify docs about GH token

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#57]
When I'm supposed to generate GH token for myself, neither docs or the interactive console wizard says how should I do that. There is only a link to complicated GitHub page and no details about what scopes should I allow, etc.

E.g. I have chosen the default settings GitHub provided me, but then my `bb t next` ends up with

```python
Traceback (most recent call last):
  File "/usr/local/bin/bb", line 5, in <module>
    main()
  File "/Library/Python/2.7/site-packages/blackbelt/tasks.py", line 30, in main
    cli()
  File "/Library/Python/2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/blackbelt/commands/t.py", line 47, in next
    n(**kwargs)
  File "/Library/Python/2.7/site-packages/blackbelt/handle_trello.py", line 255, in next_card
    prefix = get_username().lower()
  File "/Library/Python/2.7/site-packages/blackbelt/handle_github.py", line 57, in get_username
    return res.json()['login']
KeyError: 'login'
```

**Comment by pksunkara** [comment]
I just have a personal token for all my command line tools with almost all scope except the main account writing scope.

**Comment by Almad** [comment]
@honzajavorek ...reason being that I think the token approach is wrong and we should use OAuth token—but I haven't figured out how to do the workflow properly. 

Thoughts? ;)

**Comment by honzajavorek** [comment]
My thoughts:

1. Fix current situation.
2. Upgrade BB so it uses OAuth.

With figuring out how to use OAuth... Every time I do something with sb's API, I spend like 98.9898799 % of the time on figuring out how to use their OAuth and what exactly I'm supposed to put into my OAuth library. The rest is using the API. With such experience, I think we should:

1. We should do some kind of russian roulette drawing and the one who loses will go and figure this out.
2. Once we add whispread support for OAuth in Apiary docs & suff, we should NAIL IT. I mean, we should make it so awesome and easy to use, that even a monkey is going to be able to use that with her OAuth library. I vote for as much love and examples as we are able to generate for this. OAuth is a sort of crap everyone hates to use, but everyone has to use. If we can present it in usable way, people will love us.

Those are my thoughts and side-thougts ;)

**Comment by Almad** [comment]
@honzajavorek agree about 1), working on it.

Disagree about OAuth. I actually like oauth2 ;) The support for oauth in apiary has nothing to do with it; it's about desktop computer -> oauth2 server workflow, instead of easy-ish three-leg server2server workflow.

I haven't read the spec enough to get into that phase yet...but contributions welcome :P

**Comment by honzajavorek** [comment]
What I wanted to say is... From my POV, when using OAuth of any major provider, the developer experience is shitty. Docs being total mess, very unclear how to acquire token I need, how to use library I've chosen for that task, etc. So I just suggested that once we will support OAuth-enabled APIs publicly in Apiary, we should nail the presentation part of how to connect to such API.

In my reviewed opinion, OAuth itself it's not so terrible, especially for websites. The issue is that I have almost always needed to use it from CLI programs and that the dev experience (see above) was not nice. That made me associate OAuth in my mind with some apocalyptic images.

**Comment by honzajavorek** [comment]
Still not able to figure out the right token. This isn't sufficient. What am I missing? (And why is it only me and everybody else's `bb` just works? :-/ )

![screen shot 2015-02-12 at 18 27 38](https://cloud.githubusercontent.com/assets/283441/6172998/de486550-b2e4-11e4-9de3-f4b90e3fefe4.png)

**Comment by honzajavorek** [comment]
Update: I found out that the token works with basically even the most minimal scopes, but I copy-pasted it with some surrounding whitespace and that's why it did not work.

Thus, on top of improving the docs, `bb` could `.strip()` the inputs :)

**Comment by Almad** [comment]
> Thus, on top of improving the docs, bb could .strip() the inputs :)

That...makes sense :)

**Comment by abtris** [comment]
Can I close this?

**Comment by Almad** [comment]
Yup, commit should've fixed that.
