### ISSUE TITLE
BB crashes on invalid commands

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#58]
E.g. `bb next` causes the app to crash with exception.

**Comment by Almad** [comment]
This goes for multiple places (like 'Trello token expired'): no exceptions are (intentionally) caught...call for people that would refactor things into proper exceptions, catch them and provide user-friendly messages needed ;)

**Comment by abtris** [comment]
Can we close this?

```
$ bb next
Usage: bb [OPTIONS] COMMAND [ARGS]...

Error: No such command "next".
```
