### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#62]
Docs are broken. See: http://black-belt.readthedocs.org/en/latest/developer.html#merging-pull-request

--------------

Moreover, they're insufficient and hard to scan. I'd like to have:

- clear list of commands

For each command:

- command signature
- one sentence about the use case
- list of actions the command internally does (list of one or two words for each is good enough)

**Comment by Almad** [comment]
Issue discovered: actually RTD misconfigured to experiment with autodoc branch. Working on the fix.

**Comment by Almad** [comment]
@honzajavorek Please merge the referenced PR and I'll reconfigure RTD

**Comment by Almad** [comment]
[Looks slightly better](http://black-belt.readthedocs.org/en/latest/developer.html)

**Comment by Almad** [comment]
@honzajavorek enough to close?

**Comment by honzajavorek** [comment]
I guess yes, this should address what I was complaining about. If I encounter sth, I'll open another issue.

**Comment by Almad** [comment]
Thanks!
