### ISSUE TITLE
Merging locally breaks GitHub's ability to revert PR merges by button

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#68]
Currently the way `bb` merges PRs prevents GitHub to show the button "revert this merge", so reverts are more tedious and slower than they could be. I have no idea why is that, I did not dig deep into the internals, just reporting for now.

**Comment by Almad** [comment]
@honzajavorek github relies on non-fastforward merges? OMG :(

Question is whether we want to do that. Additional problem with that is we are going to have a history polluted with "Merge PR #123" commits that are empty, I personally dislike that.

**Comment by honzajavorek** [comment]
Well the issue isn't that we're missing some buttons on GitHub. The issue is that reverts are not cheap. `bb` itself could help to prepare reverts and then you don't need any buttons.

**Comment by Almad** [comment]
Yup, that makes sense.

I am just not completely sure how I'd do that. Proposals welcome :)

**Comment by honzajavorek** [comment]
It seems reverts are in git's "standard library": http://git-scm.com/blog/2010/03/02/undoing-merges.html :)

**Comment by Almad** [comment]
@honzajavorek that's useful—thanks!

**Comment by abtris** [comment]
Migrated to apiaryio/bb#38
