### ISSUE TITLE
‘bb t next-week’ doesn't work properly

### ISSUE THREAD

**Issue by Baggz** [apiaryio/black-belt#74]
Hi,

When I run `bb t next-week` it creates two columns—`Deployed by {X}` and `Verified by {X}`, where the `X` is the current date plus 7 days.

### Example

```
$ date
Tue Apr  7 16:23:18 CEST 2015
$ bb t next-week
Deployed by 2015-04-14
Verified by 2015-04-14
```

### Expected Result

`X` should be the date of the next Sunday.

```
$ date
Tue Apr  7 16:23:18 CEST 2015
$ bb t next-week
Deployed by 2015-04-12
Verified by 2015-04-12
```

#### Diff

```Diff
- Deployed by 2015-04-14
+ Deployed by 2015-04-12
```

Would it be possible to fix that?

```
$ bb version    
0.11.6
```

Thanks!

**Comment by honzajavorek** [comment]
### 1.

https://github.com/apiaryio/black-belt/blob/master/blackbelt/handle_trello.py#L323

### 2.

Take todays date. Subtract the number of days which already passed this week (this gets you 'last' Monday). Minus one day ('last' Sunday). Add one week ('next' Sunday).

```
>>> import datetime
>>> today = datetime.date.today()  # 
>>> offset = today.weekday() + 1
>>> today + datetime.timedelta(days=(-1 * offset), weeks=1)
datetime.date(2009, 10, 26)
```

Not sure what it does for corner cases (Sunday is today), etc.

**Comment by Baggz** [comment]
@honzajavorek 

Shall I open a pull request?

**Comment by honzajavorek** [comment]
@Baggz I had couple of minutes before yesterday's evening hangout, so I spent them to give pointers to hypothetical dev of this fix. If you feel so, it can be you, feel free to write it down, test it and open a PR :)

**Comment by Almad** [comment]
@baggz @honzajavorek CR welcome ;)

**Comment by honzajavorek** [comment]
I think this should be fixed now, but I leave closing of the issue up to @Baggz :)
