### ISSUE TITLE
Name mismatch

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#82]
Repo is called `black-belt`, but PyPI package is called `blackbelt`. That's confusing. I suggest renaming the repo to `blackbelt`.

**Comment by Almad** [comment]
That's intentional, and AFAIK happens often—I prefer using dashes to separate multiple words, but you can't have dashes in package/variable names, therefore one word.

I thought I saw that in multiple packages...?

**Comment by honzajavorek** [comment]
You can have dashes in package names, there are thousands like that on PyPI.

I agree it may be subjective, though. I tend to keep it consistent within my repos, because then users of that library (including me) don't need to think whether they should `pip install black-belt` or `pip install blackbelt`.

**Comment by Baggz** [comment]
@Almad 

I tend to agree with @honzajavorek.
