### ISSUE TITLE
Auto apply labels on Pr

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/black-belt#87]
It would be really great if BlackBelt could apply automatically some defined labels when issuing a pull request with `bb gh pr`

**Comment by Almad** [comment]
@XVincentX Any examples? And how it should be configured?

**Comment by XVincentX** [comment]
I was imagining that during

```bb init```

It should ask for an array of [labels](https://github.com/apiaryio/apiary/labels) to be applied automatically at each issued PR (could be more than one).

For example, I may set my bb installation to apply the **Team: Core Application** to every PR.
Does this clarify the issue?
