### ISSUE TITLE
Missing dependencies during installation

### ISSUE THREAD

**Issue by freaz** [apiaryio/black-belt#91]
After clean installation through pip the bb command complains about missing module __slacker__.

The slacker module is in requirements, but probably is not installed by pip.

Manual installation fixes the issue.

**Comment by Almad** [comment]
Can you verify it's fixed by #90 plz?

**Comment by honzajavorek** [comment]
I was affected by this bug too and I can't reproduce it anymore.

**Comment by abtris** [comment]
ok, I close.

**Comment by freaz** [comment]
Yes, works for me too.
